/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones = 'America/New_York' | 'America/Vancouver' | 'Pacific/Honolulu';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    customers: Customer;
    reservations: Reservation;
    tenants: Tenant;
    units: Unit;
    rates: Rate;
    attractions: Attraction;
    peakseasons: Peakseason;
    discounts: Discount;
    media: Media;
    Categories: Category;
    tags: Tag;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    units: {
      rates: 'rates';
      peakseasons: 'peakseasons';
      discounts: 'discounts';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    reservations: ReservationsSelect<false> | ReservationsSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    units: UnitsSelect<false> | UnitsSelect<true>;
    rates: RatesSelect<false> | RatesSelect<true>;
    attractions: AttractionsSelect<false> | AttractionsSelect<true>;
    peakseasons: PeakseasonsSelect<false> | PeakseasonsSelect<true>;
    discounts: DiscountsSelect<false> | DiscountsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    Categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  username: string;
  roles?: ('super-admin' | 'user')[] | null;
  tenants?:
    | {
        tenant: string | Tenant;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: string;
  /**
   * This is the name of the location
   */
  name: string;
  /**
   * This is the subdomain for the location (e.g. [slug].henrymitchell.net)
   */
  slug: string;
  /**
   * This is the timezone for the location
   */
  timezone: 'America/New_York' | 'America/Vancouver' | 'Pacific/Honolulu';
  icon?: (string | null) | Media;
  image?: (string | null) | Media;
  /**
   * Attractions for this tenant
   */
  attractions?: (string | Attraction)[] | null;
  /**
   * This is the description of the location
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * This Tenants contact information
   */
  contact?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  tenant?: (string | null) | Tenant;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attractions".
 */
export interface Attraction {
  id: string;
  tenant?: (string | null) | Tenant;
  name: string;
  url: string;
  image: string | Media;
  /**
   * If checked, this attraction will appear on unit view
   */
  isFavorite?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: string;
  email: string;
  name: string;
  phone?: string | null;
  addressStreet?: string | null;
  addressState?: string | null;
  addressPostalCode?: string | null;
  addressCountry?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Listing of Reservations by TENANT (Select from the dropdown if required)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservations".
 */
export interface Reservation {
  id: string;
  tenant?: (string | null) | Tenant;
  customer: string | Customer;
  unit: string | Unit;
  startDate: string;
  startDate_tz: SupportedTimezones;
  endDate: string;
  endDate_tz: SupportedTimezones;
  status: 'pending' | 'confirmed' | 'cancelled';
  quote: number;
  amountPaid: number;
  depositPaid: number;
  notes?: string | null;
  cleaningDate?: string | null;
  cleaningDate_tz?: SupportedTimezones;
  cleaningNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "units".
 */
export interface Unit {
  id: string;
  _order?: string | null;
  tenant?: (string | null) | Tenant;
  name: string;
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * If checked, you must be authenticated to view unit
   */
  isPrivate?: boolean | null;
  /**
   * If checked, this unit will be archived
   */
  isArchived?: boolean | null;
  image?: (string | null) | Media;
  coverImage?: (string | null) | Media;
  guests: number;
  bathrooms: number;
  /**
   * Size in square feet
   */
  size?: number | null;
  /**
   * Tags for this unit
   */
  tags?: (string | Tag)[] | null;
  gallery: (string | Media)[];
  rates?: {
    docs?: (string | Rate)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  peakseasons?: {
    docs?: (string | Peakseason)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Note: Discounts are not yet implemented
   */
  discounts?: {
    docs?: (string | Discount)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * This text is displayed under the calendar on a unit
   */
  taxInfo?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  _order?: string | null;
  name: string;
  slug: string;
  icon: string;
  /**
   * If checked, this tag appears in search filters
   */
  isSearchable?: boolean | null;
  /**
   * If checked, tag is an amenity
   */
  isAmenity?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The default rate for a unit before peak rate and/or discount is applied
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rates".
 */
export interface Rate {
  id: string;
  tenant?: (string | null) | Tenant;
  name: string;
  unit: string | Unit;
  price: number;
  priceType: 'night' | 'week' | 'month';
  minimumNights: number;
  startDate: string;
  startDate_tz: SupportedTimezones;
  endDate: string;
  endDate_tz: SupportedTimezones;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "peakseasons".
 */
export interface Peakseason {
  id: string;
  tenant?: (string | null) | Tenant;
  name: string;
  unit: string | Unit;
  price: number;
  priceType: 'night' | 'week' | 'month';
  minimumNights: number;
  startDate: string;
  startDate_tz: SupportedTimezones;
  endDate: string;
  endDate_tz: SupportedTimezones;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discounts".
 */
export interface Discount {
  id: string;
  tenant?: (string | null) | Tenant;
  name: string;
  unit: string | Unit;
  price: number;
  priceType: 'night' | 'week' | 'month';
  minimumNights: number;
  startDate: string;
  startDate_tz: SupportedTimezones;
  endDate: string;
  endDate_tz: SupportedTimezones;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Categories".
 */
export interface Category {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'customers';
        value: string | Customer;
      } | null)
    | ({
        relationTo: 'reservations';
        value: string | Reservation;
      } | null)
    | ({
        relationTo: 'tenants';
        value: string | Tenant;
      } | null)
    | ({
        relationTo: 'units';
        value: string | Unit;
      } | null)
    | ({
        relationTo: 'rates';
        value: string | Rate;
      } | null)
    | ({
        relationTo: 'attractions';
        value: string | Attraction;
      } | null)
    | ({
        relationTo: 'peakseasons';
        value: string | Peakseason;
      } | null)
    | ({
        relationTo: 'discounts';
        value: string | Discount;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'Categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: string | Tag;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  username?: T;
  roles?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  phone?: T;
  addressStreet?: T;
  addressState?: T;
  addressPostalCode?: T;
  addressCountry?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservations_select".
 */
export interface ReservationsSelect<T extends boolean = true> {
  tenant?: T;
  customer?: T;
  unit?: T;
  startDate?: T;
  startDate_tz?: T;
  endDate?: T;
  endDate_tz?: T;
  status?: T;
  quote?: T;
  amountPaid?: T;
  depositPaid?: T;
  notes?: T;
  cleaningDate?: T;
  cleaningDate_tz?: T;
  cleaningNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  timezone?: T;
  icon?: T;
  image?: T;
  attractions?: T;
  content?: T;
  contact?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "units_select".
 */
export interface UnitsSelect<T extends boolean = true> {
  _order?: T;
  tenant?: T;
  name?: T;
  slug?: T;
  content?: T;
  isPrivate?: T;
  isArchived?: T;
  image?: T;
  coverImage?: T;
  guests?: T;
  bathrooms?: T;
  size?: T;
  tags?: T;
  gallery?: T;
  rates?: T;
  peakseasons?: T;
  discounts?: T;
  taxInfo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rates_select".
 */
export interface RatesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  unit?: T;
  price?: T;
  priceType?: T;
  minimumNights?: T;
  startDate?: T;
  startDate_tz?: T;
  endDate?: T;
  endDate_tz?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attractions_select".
 */
export interface AttractionsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  url?: T;
  image?: T;
  isFavorite?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "peakseasons_select".
 */
export interface PeakseasonsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  unit?: T;
  price?: T;
  priceType?: T;
  minimumNights?: T;
  startDate?: T;
  startDate_tz?: T;
  endDate?: T;
  endDate_tz?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discounts_select".
 */
export interface DiscountsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  unit?: T;
  price?: T;
  priceType?: T;
  minimumNights?: T;
  startDate?: T;
  startDate_tz?: T;
  endDate?: T;
  endDate_tz?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  slug?: T;
  icon?: T;
  isSearchable?: T;
  isAmenity?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}